# Generated by Django 4.1 on 2022-08-18 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0002_alter_profile_catnumber"),
        ("Main", "0002_post_numberview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="User.profile",
            ),
        ),
    ]
