# Generated by Django 4.1 on 2022-08-16 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('catspecies', models.CharField(max_length=128)),
                ('catnumber', models.IntegerField(blank=True, max_length=128)),
                ('catimage', models.ImageField(default='default.png', upload_to='profile/')),
                ('userimage', models.ImageField(default='default.png', upload_to='profile/')),
            ],
        ),
    ]
