# Generated by Django 4.1 on 2022-08-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
